DOMAIN = {
    '51': {'datasource': {'source': '51'}},
    '22': {'datasource': {'source': '22'}},
    '21': {'datasource': {'source': '21'}},
    '-72': {'datasource': {'source': '-72'}},
    '43': {'datasource': {'source': '43'}},
    '-43': {'datasource': {'source': '-43'}},
    '46': {'datasource': {'source': '46'}},
    '-7': {'datasource': {'source': '-7'}},
    '-9': {'datasource': {'source': '-9'}},
    '-31': {'datasource': {'source': '-31'}},
    '4': {'datasource': {'source': '4'}},
    '44': {'datasource': {'source': '44'}},
    '-12': {'datasource': {'source': '-12'}},
    '8': {'datasource': {'source': '8'}},
    '24': {'datasource': {'source': '24'}},
    '31': {'datasource': {'source': '31'}},
    '71': {'datasource': {'source': '71'}},
    '-42': {'datasource': {'source': '-42'}},
    '-21': {'datasource': {'source': '-21'}},
    '-35': {'datasource': {'source': '-35'}},
    '-74': {'datasource': {'source': '-74'}},
    '35': {'datasource': {'source': '35'}},
    '1': {'datasource': {'source': '1'}},
    '-22': {'datasource': {'source': '-22'}},
    '34': {'datasource': {'source': '34'}},
    '11': {'datasource': {'source': '11'}},
    '3': {'datasource': {'source': '3'}},
    '-5': {'datasource': {'source': '-5'}},
    '72': {'datasource': {'source': '72'}},
    '-23': {'datasource': {'source': '-23'}},
    '-71': {'datasource': {'source': '-71'}},
    '-8': {'datasource': {'source': '-8'}},
    '102': {'datasource': {'source': '102'}},
    '-3': {'datasource': {'source': '-3'}},
    '42': {'datasource': {'source': '42'}},
    '-24': {'datasource': {'source': '-24'}},
    '12': {'datasource': {'source': '12'}},
    '-52': {'datasource': {'source': '-52'}},
    '-10': {'datasource': {'source': '-10'}},
    '152': {'datasource': {'source': '152'}},
    '73': {'datasource': {'source': '73'}},
    '45': {'datasource': {'source': '45'}},
    '6': {'datasource': {'source': '6'}},
    '-73': {'datasource': {'source': '-73'}},
    '33': {'datasource': {'source': '33'}},
    '-41': {'datasource': {'source': '-41'}},
    '7': {'datasource': {'source': '7'}},
    '-45': {'datasource': {'source': '-45'}},
    '5': {'datasource': {'source': '5'}},
    '61': {'datasource': {'source': '61'}},
    '41': {'datasource': {'source': '41'}},
    '52': {'datasource': {'source': '52'}},
    '101': {'datasource': {'source': '101'}},
    '-44': {'datasource': {'source': '-44'}},
    '10': {'datasource': {'source': '10'}},
    '-33': {'datasource': {'source': '-33'}},
    '-2': {'datasource': {'source': '-2'}},
    '-13': {'datasource': {'source': '-13'}},
    '-51': {'datasource': {'source': '-51'}},
    '-102': {'datasource': {'source': '-102'}},
    '-4': {'datasource': {'source': '-4'}},
    '-32': {'datasource': {'source': '-32'}},
    '-1': {'datasource': {'source': '-1'}},
    '-101': {'datasource': {'source': '-101'}},
    '-46': {'datasource': {'source': '-46'}},
    '25': {'datasource': {'source': '25'}},
    '74': {'datasource': {'source': '74'}},
    '9': {'datasource': {'source': '9'}},
    '-61': {'datasource': {'source': '-61'}},
    '2': {'datasource': {'source': '2'}},
    '-11': {'datasource': {'source': '-11'}},
    '13': {'datasource': {'source': '13'}},
    '23': {'datasource': {'source': '23'}},
    '-25': {'datasource': {'source': '-25'}},
    '-6': {'datasource': {'source': '-6'}},
    '32': {'datasource': {'source': '32'}},
    '-34': {'datasource': {'source': '-34'}},
    '-152': {'datasource': {'source': '-152'}},
    }
MONGO_HOST = 'localhost'
MONGO_PORT = 27017

MONGO_DBNAME = 'cota_smart_transit_result'

ALLOW_UNKNOWN=True

PAGINATION_LIMIT = 10000

PAGINATION_DEFAULT = 10000